# Generated by Django 4.1 on 2022-08-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=40)),
                ('l_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
