# Generated by Django 4.1 on 2022-08-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=400)),
                ('categorie', models.CharField(max_length=50)),
                ('sub_categorie', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
