# Generated by Django 4.1 on 2022-08-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='sub_categorie',
            new_name='sub_category',
        ),
    ]
