# Generated by Django 4.1 on 2022-08-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_categorie_products_category_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
