# Generated by Django 4.1 on 2022-08-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='p_name',
        ),
    ]
