# Generated by Django 4.1 on 2022-08-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_invoice_description_remove_invoice_p_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
    ]
